[project]
ref = "rlaxbloitiknjikrpbim"
name = "elite-blindagens"

[api]
url = "https://rlaxbloitiknjikrpbim.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsYXhibG9pdGlrbmppa3JwYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MzQwNzcsImV4cCI6MjA4MjQxMDA3N30.pq550K7XirbU8QnKSNOaIvs9WD-wi6cLQbS0GlH_9o8"

[database]
url = "postgresql://postgres.rlaxbloitiknjikrpbim:[password]@aws-0-sa-east-1.pooler.supabase.com:6543/postgres"
